In [63]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Data Generation
===

In [64]:
np.random.seed(10)
P, Q = (np.random.rand(i, 2) for i in (4, 5))
P_big, Q_big = (np.random.rand(i, 80) for i in (100, 120))

print(P, "\n\n", Q)

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]] 

 [[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]]


Solution
===

In [65]:
def naive(P, Q):
    """
    A naive solution for finding pairvise distances between poins in P and Q

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> naive(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement a naive solution
    D = np.zeros((P.shape[0], Q.shape[0]))
    for i in range(P.shape[0]):
        x,y = P[i]
        for j in range(Q.shape[0]):
            xx,yy = Q[j]
            D[i][j] = np.linalg.norm([x-xx, y-yy])
    return D
    # ***************************************************


test(naive)

✅ Your `naive` passed 1 tests.


### Use matching indices

Instead of iterating through indices, one can use them directly to parallelize the operations with Numpy.

In [66]:
rows, cols = np.indices((P.shape[0], Q.shape[0]))
print(rows, end="\n\n")
print(cols)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [67]:
print(P[rows.ravel()], end="\n\n")
print(Q[cols.ravel()])

[[0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]]

[[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607

In [68]:
a = np.indices((P.shape[0], Q.shape[0]))
a

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [69]:
P
P.shape

(4, 2)

In [70]:
k = P.reshape((-1,1,2))
k.shape
k


array([[[0.77132064, 0.02075195]],

       [[0.63364823, 0.74880388]],

       [[0.49850701, 0.22479665]],

       [[0.19806286, 0.76053071]]])

In [71]:
k = P[:, np.newaxis]
k.shape

(4, 1, 2)

In [72]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

ar[np.newaxis, :] == np.reshape(ar, (1,-1))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [73]:
P[:,-1]

array([0.02075195, 0.74880388, 0.22479665, 0.76053071])

In [75]:
rows, cols = np.indices((P.shape[0], Q.shape[0]))
print(P[rows.ravel()], end="\n\n")
print(Q[cols.ravel()])

[[0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]]

[[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607

In [76]:
def with_indices(P, Q):
    """
    An optimized solution using matching indices

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> with_indices(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement an optimized solution
    D = np.linalg.norm(P[:, np.newaxis] - Q, axis=2)
    # print(np.indices((P.shape[0], Q.shape[0])))

    return D
    # ***************************************************
    raise NotImplementedError

test(with_indices)

✅ Your `with_indices` passed 1 tests.


In [77]:
print(P.shape)
print(Q.shape)
print(P[:, np.newaxis,:].shape)
print((P[:, np.newaxis] - Q).shape)
print(P[:, np.newaxis] - Q)

(4, 2)
(5, 2)
(4, 1, 2)
(4, 5, 2)
[[[ 0.60220981 -0.06758786]
  [ 0.08596082 -0.9326414 ]
  [ 0.76737238 -0.49144031]
  [-0.04130032 -0.59177412]
  [ 0.04956533 -0.27112412]]

 [[ 0.4645374   0.66046407]
  [-0.05171158 -0.20458946]
  [ 0.62969997  0.23661162]
  [-0.17897273  0.13627782]
  [-0.08810708  0.45692781]]

 [[ 0.32939618  0.13645683]
  [-0.18685281 -0.7285967 ]
  [ 0.49455875 -0.28739562]
  [-0.31411395 -0.38772942]
  [-0.22324831 -0.06707942]]

 [[ 0.02895203  0.6721909 ]
  [-0.48729695 -0.19286263]
  [ 0.1941146   0.24833845]
  [-0.6145581   0.14800465]
  [-0.52369245  0.46865464]]]


In [78]:
def with_indices_2(P, Q):
    """
    An optimized solution using matching indices

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> with_indices(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement an optimized solution
    rows, cols = np.indices((P.shape[0], Q.shape[0]))
    D = np.linalg.norm(P[rows.ravel()] - Q[cols.ravel()], axis=1).reshape(P.shape[0], Q.shape[0])
    return D
    # ***************************************************
    raise NotImplementedError

test(with_indices)

✅ Your `with_indices` passed 1 tests.


### Use a library

`scipy` is the equivalent of matlab toolboxes and have a lot to offer. Actually the pairwise computation is part of the library through the `spatial` module.

In [79]:
from scipy.spatial.distance import cdist


def scipy_version(P, Q):
    """
    A solution using scipy

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)

    Returns:
        D: numpy array of shape=(p, q)

    >>> scipy_version(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    return cdist(P, Q)

### Numpy Magic

In [80]:
def tensor_broadcasting(P, Q):
    """
    A solution using tensor broadcasting

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)

    Returns:
        D: numpy array of shape=(p, q)

    >>> tensor_broadcasting(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    return np.sqrt(np.sum((P[:, np.newaxis, :] - Q[np.newaxis, :, :]) ** 2, axis=2))

# Compare methods

In [84]:
methods = [
    naive,
    # naive_2,  # This is another possible solution. Feel free to comment it out if you have only one solution.
    with_indices,
    # with_indices_2,  # This is another possible solution. Feel free to comment it out if you have only one solution.
    scipy_version,
    tensor_broadcasting,
]
timers = []
for f in methods:
    r = %timeit -o f(P, Q)
    timers.append(r)

38.7 μs ± 858 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.08 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.77 μs ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
3.54 μs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
plt.figure(figsize=(10, 6))
plt.bar(
    np.arange(len(methods)), [r.best * 1000 for r in timers], log=False
)  # Set log to True for logarithmic scale
plt.xticks(np.arange(len(methods)) + 0.2, [f.__name__ for f in methods], rotation=30)
plt.xlabel("Method")
plt.ylabel("Time (ms)")
plt.show()