In [86]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Data Generation
===

In [87]:
np.random.seed(10)
P, Q = (np.random.rand(i, 2) for i in (4, 5))
P_big, Q_big = (np.random.rand(i, 80) for i in (100, 120))

print(P, "\n\n", Q)

[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]] 

 [[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]]


Solution
===

In [88]:
def naive(P, Q):
    """
    A naive solution for finding pairvise distances between poins in P and Q

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> naive(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement a naive solution
    D = np.zeros((P.shape[0], Q.shape[0]))
    for i in range(P.shape[0]):
        x,y = P[i]
        for j in range(Q.shape[0]):
            xx,yy = Q[j]
            D[i][j] = np.linalg.norm([x-xx, y-yy])
    return D
    # ***************************************************


test(naive)

✅ Your `naive` passed 1 tests.


### Use matching indices

Instead of iterating through indices, one can use them directly to parallelize the operations with Numpy.

In [89]:
rows, cols = np.indices((P.shape[0], Q.shape[0]))
print(rows, end="\n\n")
print(cols)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [90]:
print(P[rows.ravel()], end="\n\n")
print(Q[cols.ravel()])

[[0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]]

[[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607

In [91]:
a = np.indices((P.shape[0], Q.shape[0]))
a

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [92]:
P
P.shape

(4, 2)

In [93]:
k = P.reshape((-1,1,2))
k.shape
k


array([[[0.77132064, 0.02075195]],

       [[0.63364823, 0.74880388]],

       [[0.49850701, 0.22479665]],

       [[0.19806286, 0.76053071]]])

In [94]:
k = P[:, np.newaxis]
k.shape

(4, 1, 2)

In [95]:
ar = np.array([1,2,3,4,5,6,7,8,9,10])

ar[np.newaxis, :] == np.reshape(ar, (1,-1))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [96]:
P[:,-1]

array([0.02075195, 0.74880388, 0.22479665, 0.76053071])

In [97]:
rows, cols = np.indices((P.shape[0], Q.shape[0]))
print(P[rows.ravel()], end="\n\n")
print(Q[cols.ravel()])

[[0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]
 [0.19806286 0.76053071]]

[[0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607]
 [0.16911084 0.08833981]
 [0.68535982 0.95339335]
 [0.00394827 0.51219226]
 [0.81262096 0.61252607]
 [0.72175532 0.29187607

In [98]:
def with_indices(P, Q):
    """
    An optimized solution using matching indices

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> with_indices(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement an optimized solution
    D = np.linalg.norm(P[:, np.newaxis] - Q, axis=2)
    # print(np.indices((P.shape[0], Q.shape[0])))

    return D
    # ***************************************************
    raise NotImplementedError

test(with_indices)

✅ Your `with_indices` passed 1 tests.


In [104]:
print(P.shape)
print(Q.shape)
print(P[:, np.newaxis,:].shape)
print((P[:, np.newaxis] - Q).shape)
print(P[:, np.newaxis] - Q)

(4, 2)
(5, 2)
(4, 1, 2)
(4, 5, 2)
[[[ 0.60220981 -0.06758786]
  [ 0.08596082 -0.9326414 ]
  [ 0.76737238 -0.49144031]
  [-0.04130032 -0.59177412]
  [ 0.04956533 -0.27112412]]

 [[ 0.4645374   0.66046407]
  [-0.05171158 -0.20458946]
  [ 0.62969997  0.23661162]
  [-0.17897273  0.13627782]
  [-0.08810708  0.45692781]]

 [[ 0.32939618  0.13645683]
  [-0.18685281 -0.7285967 ]
  [ 0.49455875 -0.28739562]
  [-0.31411395 -0.38772942]
  [-0.22324831 -0.06707942]]

 [[ 0.02895203  0.6721909 ]
  [-0.48729695 -0.19286263]
  [ 0.1941146   0.24833845]
  [-0.6145581   0.14800465]
  [-0.52369245  0.46865464]]]


In [154]:
print(P.shape[0], Q.shape[0])
rows, cols = np.indices((P.shape[0], Q.shape[0]))
print(rows)
print(cols)

print(rows.ravel())
print(cols.ravel())

print(P)
u = (P[rows.ravel(),:] - Q[cols.ravel(),:]) ** 2
print(u)
print(f'u shape: {u.shape}')
# u = np.sqrt(np.sum(u, axis=1))
# print(f'u shape: {u.shape}')
norm = np.linalg.norm(u, axis=1)
# print(u.shape)
# print(norm)
# print(P[rows.ravel()])
# print(P[rows])

print(norm)
print(norm.reshape(P.shape[0], Q.shape[0]))

ar = [[1,2],[3,4]]
print(np.sum(ar, axis=1))

print(np.linalg.norm(u, axis=0))

4 5
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]
 [0.49850701 0.22479665]
 [0.19806286 0.76053071]]
[[3.62656651e-01 4.56811947e-03]
 [7.38926342e-03 8.69819975e-01]
 [5.88860365e-01 2.41513582e-01]
 [1.70571630e-03 3.50196606e-01]
 [2.45672153e-03 7.35082878e-02]
 [2.15794994e-01 4.36212786e-01]
 [2.67408786e-03 4.18568486e-02]
 [3.96522050e-01 5.59850583e-02]
 [3.20312369e-02 1.85716431e-02]
 [7.76285799e-03 2.08783028e-01]
 [1.08501841e-01 1.86204668e-02]
 [3.49139711e-02 5.30853152e-01]
 [2.44588353e-01 8.25962412e-02]
 [9.86675732e-02 1.50334104e-01]
 [4.98398057e-02 4.49964894e-03]
 [8.38219937e-04 4.51840603e-01]
 [2.37458321e-01 3.71959956e-02]
 [3.76804773e-02 6.16719852e-02]
 [3.77681654e-01 2.19053751e-02]
 [2.74253785e-01 2.19637175e-01]]
u shape: (20, 2)
u shape: (20,)


In [144]:
def with_indices_2(P, Q):
    """
    An optimized solution using matching indices

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)
    Returns:
        D: numpy array of shape=(p, q)

    >>> with_indices(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    # ***************************************************
    # INSERT YOUR CODE HERE
    # TODO: implement an optimized solution
    rows, cols = np.indices((P.shape[0], Q.shape[0]))
    D = np.linalg.norm(P[rows.ravel()] - Q[cols.ravel()], axis=1).reshape(P.shape[0], Q.shape[0])
    return D
    # ***************************************************
    raise NotImplementedError

test(with_indices)

✅ Your `with_indices` passed 1 tests.


### Use a library

`scipy` is the equivalent of matlab toolboxes and have a lot to offer. Actually the pairwise computation is part of the library through the `spatial` module.

In [ ]:
from scipy.spatial.distance import cdist


def scipy_version(P, Q):
    """
    A solution using scipy

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)

    Returns:
        D: numpy array of shape=(p, q)

    >>> scipy_version(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    return cdist(P, Q)

### Numpy Magic

In [ ]:
def tensor_broadcasting(P, Q):
    """
    A solution using tensor broadcasting

    Args:
        P: numpy array of shape=(p, 2)
        Q: numpy array of shape=(q, 2)

    Returns:
        D: numpy array of shape=(p, q)

    >>> tensor_broadcasting(np.array([[0, 1]]), np.array([[2, 3], [4, 5]]))
    array([[2.82842712, 5.65685425]])
    """
    return np.sqrt(np.sum((P[:, np.newaxis, :] - Q[np.newaxis, :, :]) ** 2, axis=2))

# Compare methods

In [ ]:
methods = [
    naive,
    # naive_2,  # This is another possible solution. Feel free to comment it out if you have only one solution.
    with_indices,
    # with_indices_2,  # This is another possible solution. Feel free to comment it out if you have only one solution.
    scipy_version,
    tensor_broadcasting,
]
timers = []
for f in methods:
    r = %timeit -o f(P, Q)
    timers.append(r)

38.7 μs ± 858 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.08 μs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.77 μs ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
3.54 μs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
plt.figure(figsize=(10, 6))
plt.bar(
    np.arange(len(methods)), [r.best * 1000 for r in timers], log=False
)  # Set log to True for logarithmic scale
plt.xticks(np.arange(len(methods)) + 0.2, [f.__name__ for f in methods], rotation=30)
plt.xlabel("Method")
plt.ylabel("Time (ms)")
plt.show()